#!/bin/bash

#adb -s localhost:4444 pull /sdcard/motion.log
#adb -s localhost:4444 shell  "rm /sdcard/motion.log"
#DEVICE=025f4685dcd48c09
DEVICE="192.168.1.3:5555"
while [ 0 ]
do
    adb -s $DEVICE pull /sdcard/dictate.log 2>/dev/null
    if [ -f "dictate.log" ]
    then
        adb -s $DEVICE shell  "rm /sdcard/dictate.log 2>/dev/null" 2>/dev/null
        echo "tell application \"System Events\" to keystroke \"`cat dictate.log`\"" | osascript
        rm dictate.log 2>/dev/null
    fi
 done
